### ISSUE TITLE
license

### ISSUE THREAD

**Issue by fommil** [ScalanatorIO/akka-course#1]
gotta have a license ;-)

https://creativecommons.org/share-your-work/

I suspect you want CC-BY-ND-NC

**Comment by fommil** [comment]
actually ND might be a bit tough since the whole point is to create a derivative works (to get the tests to pass). But probably you want NC.

**Comment by rorygraves** [comment]
Good points. Will sort out today.

**Comment by rorygraves** [comment]
The branch pushed did not contain my latest README - updated now.
